settings:
  title: 'WallessPKU Status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors: 
  - id: Probe
    name: WallessPKU Probe
    url: 'https://status.drizz1e.top/'
    method: GET
    expectStatus: 401
    linkable: false 
    
  - id: Register
    name: WallessPKU Register
    description: 'Sign Up' 
    url: 'https://wallesspku.space/register'
    method: GET
    expectStatus: 200
    linkable: true 
    
  - id: US-0
    name: Olink 9929 US 0
    description: '100Mbps Sponsored by Olink Cloud' 
    url: 'http://virmach.191110.xyz/0.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: US-3
    name: XXMHost LAX CN2 GIA US 3
    description: '100Mbps' 
    url: 'http://virmach.191110.xyz/03.html'
    method: GET
    expectStatus: 200
    linkable: false
    
  - id: US-9
    name: BandwagonHost-DC2 US 9
    description: '1Gbps' 
    url: 'http://virmach.191110.xyz/09.html'
    method: GET
    expectStatus: 200
    linkable: false
    
  - id: HK-1
    name: Tencent HK 1
    description: '30Mbps' 
    url: 'http://virmach.191110.xyz/11.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: HK-2
    name: Tencent HK 2
    description: '30Mbps' 
    url: 'http://virmach.191110.xyz/12.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: HK-3
    name: Tencent HK 3
    description: '30Mbps' 
    url: 'http://virmach.191110.xyz/13.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: HK-4
    name: Tencent HK 4
    description: '30Mbps' 
    url: 'http://virmach.191110.xyz/14.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: HK-5
    name: Tencent HK 5
    description: '30Mbps' 
    url: 'http://virmach.191110.xyz/15.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: HK-6
    name: Tencent HK 6
    description: '30Mbps' 
    url: 'http://virmach.191110.xyz/16.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: HK-7
    name: Tencent HK 7
    description: '30Mbps' 
    url: 'http://virmach.191110.xyz/17.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: HK-8
    name: Tencent HK 8
    description: '30Mbps' 
    url: 'http://virmach.191110.xyz/18.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: HK-9
    name: Alibaba HK 9
    description: '30Mbps' 
    url: 'http://virmach.191110.xyz/19.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: HK-10
    name: Alibaba HK 10
    description: '30Mbps' 
    url: 'http://virmach.191110.xyz/20.html'
    method: GET
    expectStatus: 200
    linkable: false 
    
  - id: HK-11
    name: Azure HK 11
    description: '1Gbps' 
    url: 'http://virmach.191110.xyz/21.html'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: HK-12
    name: DMIT HK LITE 12
    description: '1Gbps' 
    url: 'http://virmach.191110.xyz/22.html'
    method: GET
    expectStatus: 200
    linkable: false 
    
  - id: JP-1
    name: Oracle Tokyo 1
    description: '50Mbps' 
    url: 'http://virmach.191110.xyz/26.html'
    method: GET
    expectStatus: 200
    linkable: false 
    
  - id: JP-2
    name: Oracle Tokyo 2
    description: '50Mbps' 
    url: 'http://virmach.191110.xyz/27.html'
    method: GET
    expectStatus: 200
    linkable: false 
    
  - id: JP-3
    name: Oracle Tokyo 3
    description: '0.5Gbps' 
    url: 'http://virmach.191110.xyz/28.html'
    method: GET
    expectStatus: 200
    linkable: false 
    
  - id: KR-1
    name: Oracle Chuncheon 1
    description: '50Mbps' 
    url: 'http://virmach.191110.xyz/34.html'
    method: GET
    expectStatus: 200
    linkable: false 
    
  - id: KR-2
    name: Oracle Chuncheon 2
    description: '50Mbps' 
    url: 'http://virmach.191110.xyz/35.html'
    method: GET
    expectStatus: 200
    linkable: false 
