settings:
  title: 'WallessPKU Status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors: 
  - id: Probe
    name: WallessPKU Probe
    url: 'https://status.drizz1e.top/'
    method: GET
    expectStatus: 401
    linkable: false 
    
  - id: Register
    name: WallessPKU Register
    description: 'Sign Up' 
    url: 'https://wallesspku.space/register'
    method: GET
    expectStatus: 200
    linkable: true 
    
  - id: US-0
    name: Olink 9929 US 0
    description: '100Mbps Sponsored by Olink Cloud' 
    url: 'https://v4-0.hiaoxui.work/'
    method: GET
    expectStatus: 403
    linkable: false 

  - id: US-1
    name: Oracle Ashburn US 1
    description: '50Mbps' 
    url: 'https://v4-31.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false
	
  - id: HK-A
    name: Azure HK A
    description: '1Gbps' 
    url: 'https://v4-3.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
	
  - id: HK-0
    name: ICABLE HK 0
    description: '200Mbps' 
    url: 'https://v4-1.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-1
    name: Tencent HK 1
    description: '30Mbps' 
    url: 'https://v4-11.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-2
    name: Tencent HK 2
    description: '30Mbps' 
    url: 'https://v4-12.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-3
    name: Tencent HK 3
    description: '30Mbps' 
    url: 'https://v4-13.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-4
    name: Tencent HK 4
    description: '30Mbps' 
    url: 'https://v4-14.hiaoxui.work/'
    method: GET
    expectStatus: 400
    linkable: false 

  - id: HK-5
    name: Tencent HK 5
    description: '30Mbps' 
    url: 'https://v4-15.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-6
    name: Tencent HK 6
    description: '30Mbps' 
    url: 'https://v4-16.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-7
    name: Tencent HK 7
    description: '30Mbps' 
    url: 'https://v4-17.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-8
    name: Tencent HK 8
    description: '30Mbps' 
    url: 'https://v4-18.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-9
    name: Alibaba HK 9
    description: '30Mbps' 
    url: 'https://v4-19.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-10
    name: Alibaba HK 10
    description: '30Mbps' 
    url: 'https://v4-20.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: JP-0
    name: Oracle Tokyo 0
    description: '0.5Gbps' 
    url: 'https://v4-2.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: JP-1
    name: Oracle Tokyo 1
    description: '50Mbps' 
    url: 'https://v4-26.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: JP-2
    name: Oracle Tokyo 2
    description: '50Mbps' 
    url: 'https://v4-27.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: KR-1
    name: Oracle Chuncheon 1
    description: '50Mbps' 
    url: 'https://v4-34.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: KR-2
    name: Oracle Chuncheon 2
    description: '50Mbps' 
    url: 'https://v4-35.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: AU-1
    name: Oracle Sydney 2
    description: '50Mbps' 
    url: 'https://v4-37.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
