settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:    
  - id: Register
    name: WallessPKU Register
    url: 'https://wallesspku.space/register'
    method: GET
    expectStatus: 200
    linkable: false 
    
  - id: US-0
    name: Olink 9929
    url: 'https://ipv4-0.hiaoxui.work/'
    method: GET
    expectStatus: 403
    linkable: false 

  - id: HK-1
    name: Tencent HK1
    url: 'https://ipv4-11.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-2
    name: Tencent HK2
    url: 'https://ipv4-12.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-3
    name: Tencent HK3
    url: 'https://ipv4-13.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-4
    name: Tencent HK4
    url: 'https://ipv4-14.hiaoxui.work/'
    method: GET
    expectStatus: 400
    linkable: false 

  - id: HK-5
    name: Tencent HK5
    url: 'https://ipv4-15.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-6
    name: Tencent HK6
    url: 'https://ipv4-16.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-7
    name: Tencent HK7
    url: 'https://ipv4-17.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-8
    name: Tencent HK8
    url: 'https://ipv4-18.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-9
    name: Ali HK9
    url: 'https://ipv4-19.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: HK-10
    name: Ali HK10
    url: 'https://ipv4-20.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: HK-11
    name: Azure HK
    url: 'https://ipv4-21.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 

  - id: JP-1
    name: Oracle Tokyo 1
    url: 'https://ipv4-26.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: JP-2
    name: Oracle Tokyo 2
    url: 'https://ipv4-27.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: JP-3
    name: Oracle Tokyo 3
    url: 'https://ipv4-28.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: KR-1
    name: Oracle Chuncheon 1
    url: 'https://ipv4-34.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: KR-2
    name: Oracle Chuncheon 2
    url: 'https://ipv4-35.hiaoxui.work/'
    method: GET
    expectStatus: 503
    linkable: false 
    
  - id: BandwagonHost-DC6
    name: BandwagonHost-DC6
    url: 'https://my.191110.xyz/'
    method: GET
    expectStatus: 200
    linkable: false 
    
  - id: BandwagonHost-DC2
    name: BandwagonHost-DC2
    url: 'https://www.191110.xyz/'
    method: GET
    expectStatus: 200
    linkable: false 

  - id: VirMach-Chicago
    name: VirMach Chicago
    url: 'http://172.245.241.129'
    method: GET
    expectStatus: 301
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false 
